import { Type } from 'class-transformer';
import {
  IsArray, IsEnum, IsOptional, IsString, IsUUID,
  ValidateNested, IsInt, Min, ArrayMinSize,
} from 'class-validator';
import { PaymentMethod } from '../../../database/entities';

export class SaleItemDto {
  @IsUUID()
  productId: string;

  @IsInt()
  @Min(1)
  quantity: number;
}

export class CreateSaleDto {
  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => SaleItemDto)
  items: SaleItemDto[];

  @IsEnum(PaymentMethod)
  paymentMethod: PaymentMethod;

  /**
   * Unique key generated by the POS terminal per sale attempt.
   * Retries must send the same key to avoid duplicate sales.
   */
  @IsString()
  idempotencyKey: string;

  @IsOptional()
  @IsString()
  notes?: string;
}
